Updated with Backend
Nexus-Optima/Inventory-Management-UI pull request #6
Opened 2024-04-01 08:09 UTC by abhilakshm

2024-04-01 17:56 UTC, kaivan-s commented on src/Components/Summary.js
> +          `${process.env.REACT_APP_URL}?client_name=Abhilaksh Misra`
client_name should be dynamic.

2024-04-01 17:57 UTC, kaivan-s commented on src/Components/Summary.js
> +        console.error("Error fetching data:", error);
Lets display message on the screen instead of console.error.

2024-04-01 17:58 UTC, kaivan-s commented on src/Components/Summary.js
> +    }
Explain logic in description.

2024-04-01 17:59 UTC, kaivan-s requested changes
Added a few comments, Please check.

2024-04-01 17:59 UTC, kaivan-s commented
Please add the screenshot as well for the UI so we have the reference.

2024-04-02 11:07 UTC, abhilakshm commented on src/Components/Summary.js
> +    }
1.calculatePriorityPercentages: This function calculates the percentage of each priority level in the dataset. It first determines the total number of items in the dataset (totalItems). Then, it iterates over each item and updates a priorityCounts object, counting the occurrences of each priority level. Finally, it calculates the percentage of each priority level by dividing the count of items for that priority by the total number of items and multiplying by 100. The resulting percentages are stored in the percentages object with the priority levels as keys. These percentages are then set in the priorityPercentages state variable using setPriorityPercentages.

2.calculateStockPercentages: Similarly, this function calculates the percentage of each stock category in the dataset. It follows a similar logic to calculatePriorityPercentages. It first determines the total number of items in the dataset (totalItems). Then, it iterates over each item and updates a stockCounts object, counting the occurrences of each stock category. Finally, it calculates the percentage of each stock category by dividing the count of items for that category by the total number of items and multiplying by 100. The resulting percentages are stored in the percentages object with the stock categories as keys. These percentages are then set in the stockPercentages state variable using setStockPercentages.

2024-04-04 07:28 UTC, kaivan-s commented on src/Components/Summary.js
> +      try {
Add TODO here.

2024-04-04 07:30 UTC, kaivan-s commented on src/Components/Summary.js
> +    }
Can we think of some way to optimize this? Because we will be having thousands of data points and it might take some time on JS end to calculate those things.

2024-04-04 07:30 UTC, kaivan-s commented on src/constants.js
> +  };
Update this as well based on discussion.

2024-04-04 07:31 UTC, kaivan-s requested changes
Added a few comments please check.

2024-04-09 10:05 UTC, kaivan-s commented on src/Components/ActionPlan.js
> +                  maxHeight: "70vh",
Let's avoid hard coding. Not sure how it would look in a mobile.

2024-04-09 10:07 UTC, kaivan-s reviewed
I am still not sure about percentages. Have we checked how it looks in a mobile screen ?

2024-04-17 10:14 UTC, merged